project_id = "mbwreoglhudppiwaxlsp"

[functions.analyze-project]
verify_jwt = false

[functions.research-incentives]
verify_jwt = false

[functions.research-copro]
verify_jwt = false

[functions.project-incentive-insights]
verify_jwt = false

[functions.refresh-trends]
verify_jwt = false

[functions.analyze-note]
verify_jwt = false

[functions.extract-characters]
verify_jwt = false

[functions.extract-documents]
verify_jwt = false

[functions.extract-scenes]
verify_jwt = false

[functions.research-person]
verify_jwt = false

[functions.script-coverage]
verify_jwt = false

[functions.comp-analysis]
verify_jwt = false

[functions.smart-packaging]
verify_jwt = false
